version: "3.3"
# lsd.czeps.org docker-compose.yml
# made by brozkeff, martin.malec@czeps.org
# version 02 September 2017, temporarily removed proxy to make dokuwiki directly accessible

services:
  dokuwiki:
    ## ORIGINAL RUN COMMAND:
    ## sudo docker run -d --expose=80 --volume /srv/bitnami-dokuwiki/dokuwiki-persistence:/bitnami/dokuwiki --volume /srv/bitnami-dokuwiki/apache-persistence:/bitnami/apache --volume /srv/bitnami-dokuwiki/php-persistence:/bitnami/php -e "CERT_NAME=wiki.czeps.org" -e "VIRTUAL_HOST=wiki.czeps.org" -e "LETSENCRYPT_HOST=wiki.czeps.org" -e "LETSENCRYPT_EMAIL=info@czeps.org"  --name dokuwiki bitnami/dokuwiki:latest

    image: bitnami/dokuwiki:latest
    container_name: dokuwiki
    volumes:
      - /srv/bitnami-dokuwiki:/bitnami

    environment:
      - VIRTUAL_HOST=wiki.czeps.org
      - LETSENCRYPT_HOST=wiki.czeps.org
      - LETSENCRYPT_EMAIL=info@czeps.org
    expose:
      - "80"
    ports:
      - "8080:80"

  certbot:
    image: deliverous/certbot
    container_name: certbot
    volumes:
      - /srv/letsencrypt-certs:/etc/letsencrypt
      - /srv/letsencrypt-challenge:/data/letsencrypt
    command: certonly --webroot --webroot-path=/data/letsencrypt -d wiki.czeps.org --agree-tos -m info@czeps.org --staging --no-eff-email
